## Amiga 500 for MEGA65 (AExp)
##
## Core specific constraints
##
## This machine is based on Minimig-AGA_MiSTer (MiSTer-devel/Minimig-AGA_MiSTer)
## Powered by MiSTer2MEGA65
## MEGA65 port done in 2026 and licensed under GPL v3


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)
##
## main_clk is the Amiga's 28.375 MHz master clock (PAL 28.37516 MHz, -5.6 ppm).
## Everything in the core runs on it; the 7.09 MHz bus timing is made of clock
## enables (amiga_clk.v), and cpu_wrapper.v contains a (pruned with cpucfg=00)
## negedge-clk FSM - both edges of main_clk are therefore timed automatically.
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
# Add more clocks here, if needed

## Notes for timing review after the first synthesis (do not enable blindly):
## - rtl/minimig_m68k_bridge.v uses a logic signal (_as_and_cs) as an async
##   preset (infers FDPE) - check the timing report for it.
## - rtl/paula_floppy.v has 'posedge clk or negedge IO_ENA' blocks; IO_FPGA is
##   tied '0' in this milestone, so these registers stay cleared.
